export const currencyMap = {
  'Angola':                   'AOA',
  'Antigua and Barbuda':      'XCD',
  'Argentina':                'ARS',
  'Armenia':                  'AMD',
  'Australia':                'AUD',
  'Bahamas':                  'BSD',
  'Belarus':                  'BYN',
  'Bhutan':                   'BTN',
  'Bolivia':                  'BOB',
  'Botswana':                 'BWP',
  'Brazil':                   'BRL',
  'Bulgaria':                 'BGN',
  'Burundi':                  'BIF',
  'Cabo Verde':               'CVE',
  'Cambodia':                 'KHR',
  'Chile':                    'CLP',
  'China':                    'CNY',
  'Colombia':                 'COP',
  'Congo':                    'CDF',
  'Costa Rica':               'CRC',
  'Croatia':                  'HRK',
  'Cuba':                     'CUP',
  'Czech Republic':           'CZK',
  'Denmark':                  'DKK',
  'Dominican Republic':       'DOP',
  'Eritrea':                  'ERN',
  'Eswatini':                 'SZL',
  'Ethiopia':                 'ETB',
  'Fiji':                     'FJD',
  'Georgia':                  'GEL',
  'Ghana':                    'GHS',
  'Guatemala':                'GTQ',
  'Guyana':                   'GYD',
  'Haiti':                    'HTG',
  'Honduras':                 'HNL',
  'Hungary':                  'HUF',
  'Iceland':                  'ISK',
  'India':                    'INR',
  'Israel':                   'ILS',
  'Jamaica':                  'JMD',
  'Japan':                    'JPY',
  'Kenya':                    'KES',
  'Korea, North':             'KPW',
  'Korea, South':             'KRW',
  'Kuwait':                   'KWD', 
  'Laos':                     'LAK',
  'Lebanon':                  'LBP',
  'Lesotho':                  'LSL',
  'Liberia':                  'LRD',
  'Madagascar':               'MGA',
  'Malawi':                   'MWK',
  'Malaysia':                 'MYR', 
  'Maldives':                 'MVR', 
  'Mauritius':                'MUR',
  'Mexico':                   'MXN',
  'Moldova':                  'MDL',
  'Mongolia':                 'MNT',
  'Morocco':                  'MAD', 
  'Mozambique':               'MZN',
  'Myanmar':                  'MMK',
  'Namibia':                  'NAD',
  'Nepal':                    'NPR',
  'New Zealand':              'NZD',
  'Nicaragua':                'NIO',
  'North Macedonia':          'MKD',
  'Norway':                   'NOK',
  'Oman':                     'OMR', 
  'Pakistan':                 'PKR', 
  'Panama':                   'PAB',
  'Papua New Guinea':         'PGK',
  'Paraguay':                 'PYG',
  'Peru':                     'PEN',
  'Philippines':              'PHP',
  'Poland':                   'PLN',
  'Qatar':                    'QAR', 
  'Romania':                  'RON',
  'Russia':                   'RUB',
  'Rwanda':                   'RWF',
  'Samoa':                    'WST',
  'Sao Tome and Principe':    'STN',
  'Serbia':                   'RSD',
  'Seychelles':               'SCR',
  'Sierra Leone':             'SLL',
  'Singapore':                'SGD',
  'Solomon Islands':          'SBD',
  'South Africa':             'ZAR',
  'Sri Lanka':                'LKR',
  'Suriname':                 'SRD',
  'Tanzania':                 'TZS',
  'Thailand':                 'THB',
  'Togo':                     'XOF',
  'Tonga':                    'TOP',
  'Trinidad and Tobago':      'TTD',
  'Turkey':                   'TRY', 
  'Tuvalu':                   'AUD',
  'Uganda':                   'UGX',
  'Ukraine':                  'UAH',
  'United Arab Emirates':     'AED',
  'United States':            'USD',
  'Uruguay':                  'UYU',
  'Vanuatu':                  'VUV',
  'Venezuela':                'VES',
  'Vietnam':                  'VND',
  'Zambia':                   'ZMW',
  'Zimbabwe':                 'ZWL'
};
